#+ summary:  How many resources have been gathered by means of catalogs? 
#+ tags:
#+    - catalogs

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?catalogueLabel (count(?resource) AS ?count)  
FROM <http://data.open.ac.uk/context/mudow>
WHERE {
  ?catalogue rdfs:label ?catalogueLabel ; <http://purl.org/spar/datacite/hasGeneralResourceType> ?catalogueType .
  ?catalogueType rdfs:label ?typeLabel .
  filter(?typeLabel="Catalogue") .
  ?resource <http://purl.org/spar/fabio/hasSubjectTerm> ?catalogue
}
