#+ summary:  What is tehir scale?
#+ tags:
#+    - digital-editions

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT  ?extentLabel (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/musow>
WHERE {
   ?resource <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://purl.org/dc/terms/extent> ?extent. 
   ?resourceType rdfs:label ?typeLabel . filter(?typeLabel='Digital edition') .
   ?extent rdfs:label ?extentLabel .
}
GROUP BY ?extentLabel ?count
ORDER BY ?extentLabel DESC(?count)  
