#+ summary:  Do they offer playable objects?
#+ tags:
#+    - digital-editions

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/musow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://schema.org/featureList> 
                <http://data.open.ac.uk/musow/ontology/feature/playable> . 
   ?resourceType rdfs:label ?typeLabel . filter(?typeLabel='Digital edition') .
}
