#+ summary:  Which are the claimed tasks of digital editions?
#+ tags:
#+    - digital-editions

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?taskLabel (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/musow>
WHERE {
   ?resource rdfs:label ?resourceLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://data.open.ac.uk/musow/ontology/situation/task> ?task .
   ?resourceType rdfs:label ?typeLabel . filter(?typeLabel='Digital edition') .
   ?task rdfs:label ?taskLabel .
}
GROUP BY ?taskLabel ?count
ORDER BY DESC(?count)
