#+ summary:  What is the purpose of such resources? Learning or research? 
#+ tags:
#+    - libraries-repositories

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?purposeLabel (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/mudow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://www.w3.org/ns/oa#hasPurpose> ?purpose .
   ?resourceType rdfs:label ?typeLabel . filter(?typeLabel IN ("Repository", "Digital library")) .
   ?purpose rdfs:label ?purposeLabel .
}
GROUP BY ?purposeLabel ?count
ORDER BY DESC(?count)
