#+ summary:  What is the scale of repositories and digital libraries?
#+ tags:
#+    - libraries-repositories

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?extentLabel (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/musow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://purl.org/dc/terms/extent> ?extent .
   {?resourceType rdfs:label ?typeLabel . filter(?typeLabel="Repository")} 
      UNION 
   {?resourceType rdfs:label ?typeLabel . filter(?typeLabel="Digital Library")} .
   ?extent rdfs:label ?extentLabel .
}
GROUP BY ?extentLabel ?count
ORDER BY ?count
