#+ summary:  Is data published in repositories or digital libraries reused in other projects? 
#+ tags:
#+    - libraries-repositories

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?resourceLabel (count(DISTINCT ?otherResource) AS ?count)
FROM <http://data.open.ac.uk/context/mudow>
WHERE {
   ?resource rdfs:label ?resourceLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType .
   ?resourceType rdfs:label ?typeLabel . filter(?typeLabel IN ("Repository", "Digital library")) .
   ?resource ^<http://www.w3.org/2004/02/skos/core#related> ?otherResource .
}
GROUP BY ?resourceLabel ?count
ORDER BY DESC(?count)
