#+ summary:  Which are the most/least used data formats? 
#+ tags:
#+    - libraries-repositories

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?formatLabel (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/musow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://data.open.ac.uk/musow/ontology/scope/format> ?format .
   {?resourceType rdfs:label ?typeLabel . filter(?typeLabel="Repository")} 
      UNION 
   {?resourceType rdfs:label ?typeLabel . filter(?typeLabel="Digital Library")} .
   ?format rdfs:label ?formatLabel .
}
GROUP BY ?formatLabel ?count
ORDER BY DESC(?count)
