#+ summary:  How many of them provide digitizations of scores or songs? Results refere to a combination of image formats that are generally used to publish music contents. 
#+ tags:
#+    - libraries-repositories

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/musow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://data.open.ac.uk/musow/ontology/scope/format> ?format .
   {?resourceType rdfs:label ?typeLabel . filter(?typeLabel="Repository")} 
      UNION 
   {?resourceType rdfs:label ?typeLabel . filter(?typeLabel="Digital Library")} .
   filter( str(?format) IN ("http://data.open.ac.uk/musow/pdf" , "http://data.open.ac.uk/musow/jpg", 
    "http://data.open.ac.uk/musow/tiff", "http://data.open.ac.uk/musow/iiif", "http://data.open.ac.uk/musow/gif", "http://data.open.ac.uk/musow/png", "http://data.open.ac.uk/musow/djvu"))
}
