#+ summary:  How many of them provide audio files?
#+ tags:
#+    - libraries-repositories

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/mudow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://data.open.ac.uk/mudow/ontology/scope/format> ?format .
   {?resourceType rdfs:label ?typeLabel . filter(?typeLabel="Repository")} 
      UNION 
   {?resourceType rdfs:label ?typeLabel . filter(?typeLabel="Digital Library")} .
   filter( str(?format) IN ("http://data.open.ac.uk/mudow/midi" , "http://data.open.ac.uk/mudow/mp3", 
    "http://data.open.ac.uk/mudow/audio", "http://data.open.ac.uk/mudow/video", "http://data.open.ac.uk/mudow/finale", "http://data.open.ac.uk/mudow/sibelius", "http://data.open.ac.uk/mudow/flac"))
}
