#+ summary:  How many datasets on musical data are available on the web?
#+ tags:
#+    - datasets

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/musow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType .
   ?resourceType rdfs:label ?typeLabel . filter(?typeLabel='Dataset') .
}
