#+ summary:  In which formats are datasets released?
#+ tags:
#+    - datasets

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?formatLabel (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/mudow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://data.open.ac.uk/mudow/ontology/scope/format> ?format .
   ?resourceType rdfs:label ?typeLabel . filter(?typeLabel='Dataset') .
   ?format rdfs:label ?formatLabel .
}
GROUP BY ?formatLabel ?count
ORDER BY DESC(?count)
