#+ summary:  What is the scope of datasets?
#+ tags:
#+    - datasets

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?scopeLabel (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/musow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://www.w3.org/ns/oa#hasScope> ?scope .
   ?resourceType rdfs:label ?typeLabel . filter(?typeLabel='Dataset') .
   ?scope rdfs:label ?scopeLabel .
}
GROUP BY ?scopeLabel ?count
ORDER BY DESC(?count)
