#+ summary:  What is the realtion between the usage of formats and scale of resources?
#+ tags:
#+    - formats

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?extentLabel ?formatLabel (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/musow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType ;
             <http://purl.org/dc/terms/extent> ?extent ; 
             <http://data.open.ac.uk/musow/ontology/scope/format> ?format .
   ?resourceType rdfs:label ?typeLabel . 
   ?extent rdfs:label ?extentLabel . ?format rdfs:label ?formatLabel .
}
GROUP BY ?extentLabel ?formatLabel ?count
ORDER BY ?extentLabel DESC(?count)
