#+ summary:  How many resources have been included in the survey?
#+ tags:
#+    - general

SELECT (COUNT(?s) as ?count)
FROM <http://data.open.ac.uk/context/mudow>
WHERE {
   ?s <http://xmlns.com/foaf/0.1/homepage> ?o .
}
