#+ summary:  Which types of resource have been included in the survey?
#+ tags:
#+    - general

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?label (count(DISTINCT ?resource) AS ?count) 
FROM <http://data.open.ac.uk/context/musow>
WHERE {
   	?resource <http://purl.org/spar/datacite/hasGeneralResourceType> ?type .
   	?type rdfs:label ?label .
}
GROUP BY ?label ?count
ORDER BY desc(?count)
