#+ summary:  What is the main data source of gathered resources? Results refer to the original musical object described in the resource i.e. audio files, metadata or symbolic notations.
#+ tags:
#+    - general

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?categoryLabel (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/mudow>
WHERE {
  ?resource <http://dbpedia.org/ontology/category> ?category .
  ?category rdfs:label ?categoryLabel .
}
GROUP BY ?categoryLabel
ORDER BY ?categoryLabel
