#+ summary:  How many resources are not targeted on researchers? 
#+ tags:
#+    - general

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT (count(DISTINCT ?resource) AS ?count) 
FROM <http://data.open.ac.uk/context/musow>
WHERE {
    ?resource <http://purl.org/dc/terms/audience> ?typeaudience .
    ?typeaudience rdfs:label ?audience .
    FILTER(?audience NOT IN ('researchers')).
}
