#+ summary:  How much of the content on the Web representing symbolic notation is machine readable?
#+ tags:
#+    - symbolic-notation

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT DISTINCT ?extentLabel (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/mudow>
WHERE {
   ?resource <http://schema.org/featureList> 
                <http://data.open.ac.uk/mudow/ontology/feature/symbolic-machine-readable> ;
             <http://purl.org/dc/terms/extent> ?extent.
  ?extent rdfs:label ?extentLabel . 
}
GROUP BY ?extentLabel ?count
ORDER BY desc(?count)
