#+ summary:  How many ontologies and schemas are availabel for describing music domain?
#+ tags:
#+    - ontologies

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT (count(DISTINCT ?resource) AS ?count)
FROM <http://data.open.ac.uk/context/mudow>
WHERE {
   ?resource rdfs:label ?catalogueLabel ; 
             <http://purl.org/spar/datacite/hasGeneralResourceType> ?resourceType .
  ?resourceType rdfs:label ?typeLabel . filter(?typeLabel in ('Ontology', 'Schema')) .
}
